pipeline:
  build_docker_image:
    image: docker:19.03.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t centos-base:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    environment:
      - WHITELIST=CVE-2019-5827
    image_name: centos-base:${DRONE_COMMIT_SHA}
    local_image: true
    when:
      event: push

  image_to_quay:
    image: docker:19.03.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag centos-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-base:$${DRONE_COMMIT_SHA}
      - docker tag centos-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-base:latest
      - docker push quay.io/ukhomeofficedigital/centos-base:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/centos-base:latest
    when:
      event: push
      branch: master

  tagged_image_to_quay:
    image: docker:19.03.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag centos-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-base:$${DRONE_TAG}
      - docker tag centos-base:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/centos-base:latest
      - docker push quay.io/ukhomeofficedigital/centos-base:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/centos-base:latest
    when:
      event: tag
